
<<<<<<< HEAD
import com.lowagie.text.Chunk;
import com.lowagie.text.Document;
import com.lowagie.text.DocumentException;
import com.lowagie.text.Element;
import com.lowagie.text.Font;
import com.lowagie.text.Paragraph;
import com.lowagie.text.Phrase;
import com.lowagie.text.pdf.PdfPCell;
import com.lowagie.text.pdf.PdfPTable;
import com.lowagie.text.pdf.PdfWriter;
import java.awt.Color;
import java.awt.Dimension;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.text.DateFormat;
import java.text.ParseException;
=======
>>>>>>> c84378042d77448b19c911bc78cd7f4c6129efb1
import javax.swing.text.AbstractDocument;
import javax.swing.text.AttributeSet;
import javax.swing.text.BadLocationException;
import javax.swing.text.DocumentFilter;
<<<<<<< HEAD
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.time.ZoneId;
import java.util.Calendar;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
=======
>>>>>>> c84378042d77448b19c911bc78cd7f4c6129efb1

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author kai_s
 */
public class Kapitalrechner extends javax.swing.JFrame {

    double Startkapital;
    double Einlagen;
    double Zinssatz;
    double Auszahlung;
    double Resultat;
<<<<<<< HEAD
    double Saldo;
    double Zähler;

    public Kapitalrechner() {
        initComponents();
        setLocationRelativeTo(null);
        setMinimumSize(new Dimension(840, 750));
        auszahlung.setEnabled(false);
        einlage.setEnabled(false);
        zinssatz.setEnabled(false);
        einzahlen.setEnabled(false);
        auszahlen.setEnabled(false);
        zinsändern.setEnabled(false);
=======

    public Kapitalrechner() {
        initComponents();

        jTextField7.setEnabled(false);
        jTextField8.setEnabled(false);
        jTextField6.setEnabled(false);
        jButton3.setEnabled(false);
        jButton2.setEnabled(false);
        jButton4.setEnabled(false);
>>>>>>> c84378042d77448b19c911bc78cd7f4c6129efb1
        jTextField5Buchstaben(10);
        jTextField8Buchstaben(10);
        jTextField7Buchstaben(10);
        jTextField6Buchstaben(10);
<<<<<<< HEAD
        jTextField3Buchstaben(6);
        Zähler = 1;
        Startkapital = 0;
        Saldo = 0;
        Zinssatz = 0;
        Auszahlung = 0;
        Resultat = 0;
=======
>>>>>>> c84378042d77448b19c911bc78cd7f4c6129efb1
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
<<<<<<< HEAD

=======
    @SuppressWarnings("unchecked")
>>>>>>> c84378042d77448b19c911bc78cd7f4c6129efb1
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        head = new javax.swing.JPanel();
        titel = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel5 = new javax.swing.JLabel();
<<<<<<< HEAD
        startkapital = new javax.swing.JTextField();
        zinssatz = new javax.swing.JTextField();
        auszahlung = new javax.swing.JTextField();
        einlage = new javax.swing.JTextField();
=======
        jTextField5 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jTextField7 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jTextField8 = new javax.swing.JTextField();
>>>>>>> c84378042d77448b19c911bc78cd7f4c6129efb1
        jButton1 = new javax.swing.JButton();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
<<<<<<< HEAD
        auszahlen = new javax.swing.JButton();
        einzahlen = new javax.swing.JButton();
        zinsändern = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablePensionBut = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();
        zinssatzFeld = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        datumFeld = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
=======
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
>>>>>>> c84378042d77448b19c911bc78cd7f4c6129efb1

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        head.setBackground(new java.awt.Color(51, 188, 209));

        titel.setBackground(new java.awt.Color(0, 0, 0));
        titel.setFont(new java.awt.Font("Lucida Console", 0, 48)); // NOI18N
        titel.setText("Piler");

        javax.swing.GroupLayout headLayout = new javax.swing.GroupLayout(head);
        head.setLayout(headLayout);
        headLayout.setHorizontalGroup(
            headLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(titel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        headLayout.setVerticalGroup(
            headLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(titel)
                .addContainerGap(12, Short.MAX_VALUE))
        );

        jLabel1.setText("Name:");

        jLabel2.setText("Vorname:");

<<<<<<< HEAD
        jLabel3.setText("Wohnort:");

        jLabel4.setText("PLZ");

        jLabel5.setText("Startkapital:");

=======
        jLabel3.setText("PLZ:");

        jLabel4.setText("Wohnort:");

        jLabel5.setText("Startkapital:");

        jLabel6.setText("Zinssatz:");

        jLabel7.setText("Einlage:");

        jLabel8.setText("Auszahlung:");

>>>>>>> c84378042d77448b19c911bc78cd7f4c6129efb1
        jButton1.setText("Zurück zur Startseite");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setText("Auszahlen");
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setText("Einzahlen");
        jRadioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton2ActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioButton3);
        jRadioButton3.setText("Zinsänderung");
        jRadioButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton3ActionPerformed(evt);
            }
        });

<<<<<<< HEAD
        auszahlen.setText("Auszahlen");
        auszahlen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                auszahlenActionPerformed(evt);
            }
        });

        einzahlen.setText("Einzahlen");
        einzahlen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                einzahlenActionPerformed(evt);
            }
        });

        zinsändern.setText("Zins ändern");
        zinsändern.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                zinsändernActionPerformed(evt);
            }
        });
=======
        jButton2.setText("Auszahlen");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Einzahlen");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("Zins ändern");
>>>>>>> c84378042d77448b19c911bc78cd7f4c6129efb1

        jButton5.setText("Saldo berechnen");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

<<<<<<< HEAD
        tablePensionBut.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Datum", "Bezeichnung", "Zins", "Betrag"
            }
        ));
        jScrollPane1.setViewportView(tablePensionBut);

        jButton2.setText("Zu PDF exportieren");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        zinssatzFeld.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                zinssatzFeldActionPerformed(evt);
            }
        });

        jLabel12.setText("Zinssatz");

        jLabel13.setText("Datum:");

        datumFeld.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                datumFeldActionPerformed(evt);
            }
        });

        jLabel6.setText("dd.mm.yyy");

=======
>>>>>>> c84378042d77448b19c911bc78cd7f4c6129efb1
        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(head, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jSeparator1)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
<<<<<<< HEAD
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 337, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jRadioButton3)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jRadioButton1)
                                .addComponent(jRadioButton2)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(zinssatz, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
                            .addComponent(auszahlung, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(einlage, javax.swing.GroupLayout.Alignment.LEADING)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jLabel6))
                            .addComponent(datumFeld, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(647, 647, 647)
                .addComponent(jLabel10))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(startkapital, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel12)
                        .addGap(6, 6, 6)
                        .addComponent(zinssatzFeld, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
=======
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8)
                            .addComponent(jLabel6)
                            .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jTextField6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
                                    .addComponent(jTextField7, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextField8, javax.swing.GroupLayout.Alignment.LEADING))
                                .addGap(34, 34, 34)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jRadioButton3)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel10)
                                        .addGap(288, 288, 288))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jRadioButton1)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jRadioButton2)
                                                .addGap(113, 113, 113)
                                                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGap(0, 0, Short.MAX_VALUE))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton1))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
>>>>>>> c84378042d77448b19c911bc78cd7f4c6129efb1
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel4)
<<<<<<< HEAD
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jButton5)
                                .addGap(110, 110, 110))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(24, 24, 24)
                                        .addComponent(jLabel13))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(einzahlen, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(auszahlen)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(zinsändern)))
                                .addGap(78, 78, 78)))
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 402, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 62, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButton2)
                        .addGap(188, 188, 188))))
=======
                        .addGap(18, 18, 18)
                        .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
>>>>>>> c84378042d77448b19c911bc78cd7f4c6129efb1
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(head, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
<<<<<<< HEAD
                    .addComponent(jLabel3)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(startkapital, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(zinssatzFeld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(einlage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jRadioButton2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(auszahlung, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jRadioButton1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(zinssatz, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jRadioButton3)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13)
                            .addComponent(datumFeld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel6)
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(einzahlen)
                            .addComponent(auszahlen)
                            .addComponent(zinsändern))
                        .addGap(46, 46, 46)
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(49, 49, 49)
                        .addComponent(jButton5))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addComponent(jButton1)
=======
                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jRadioButton2)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(jRadioButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(jRadioButton3)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jButton4)
                    .addComponent(jButton3)
                    .addComponent(jButton5)
                    .addComponent(jButton1))
>>>>>>> c84378042d77448b19c911bc78cd7f4c6129efb1
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.dispose();
        Startseite Startseite = new Startseite();
        Startseite.setVisible(true);
        setLocationRelativeTo(null);
    }//GEN-LAST:event_jButton1ActionPerformed

<<<<<<< HEAD
    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        DateFormat dateFormat = new SimpleDateFormat("dd.MM.yyyy");
        Date date = new Date();
        jLabel11.setText("Dein Saldo am" + " " + dateFormat.format(date) + " " + " " + "beträgt"+ " " + Saldo + " " + "CHF");
    }//GEN-LAST:event_jButton5ActionPerformed

    private void auszahlenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_auszahlenActionPerformed
        DateFormat dateFormat = new SimpleDateFormat("dd.MM.yyyy");
        Date date = new Date();
        String StartkapitalS = startkapital.getText();
        Startkapital = Double.parseDouble(StartkapitalS);

        String AuszahlungS = auszahlung.getText();
        Auszahlung = Double.parseDouble(AuszahlungS);

        while (Zähler < 1) {
            Saldo += Startkapital;
            Zähler = 2;
        }

        Saldo -= Auszahlung;

        System.out.println(Saldo);

        jLabel11.setText("Sie haben am" + " " + dateFormat.format(date) + " " + " " + AuszahlungS + " " + "CHF" + " " + "ausgezahlt");
        
        String bezeichnung = "Auszahlung";
                LocalDate datum = java.time.LocalDate.now();
        Date lokalesDatum = Date.from(datum.atStartOfDay(ZoneId.systemDefault()).toInstant());
        String formattedDatum = dateFormat.format(lokalesDatum);
        
        if(auszahlung.getText().equals("")){
            JOptionPane.showMessageDialog(this, "Please fill in the empty field");
        } else {
        String Daten [] = {formattedDatum, bezeichnung, "", auszahlung.getText()};
            DefaultTableModel tblModel = (DefaultTableModel)tablePensionBut.getModel();   
            tblModel.addRow(Daten);
            auszahlung.setText("");
        }
    }//GEN-LAST:event_auszahlenActionPerformed

    private void einzahlenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_einzahlenActionPerformed
DefaultTableModel tblModel = (DefaultTableModel) tablePensionBut.getModel();
        DateFormat dateFormat = new SimpleDateFormat("dd.MM.yyyy");
        String datum = datumFeld.getText();
        String formattedDatum = "";
try{
    // Datum parsen
    Date parsedDate = dateFormat.parse(datum);
    formattedDatum = dateFormat.format(parsedDate);
        String EinlagenS = einlage.getText();
        Einlagen = Double.parseDouble(EinlagenS);

        String StartkapitalS = startkapital.getText();
        Startkapital = Double.parseDouble(StartkapitalS);

        while (Zähler < 2) {
            Saldo += Startkapital;
            Zähler = 2;
        }

        Saldo += Einlagen;

        System.out.println(Saldo);

        jLabel11.setText("Sie haben am" + " " + formattedDatum + " " + " " + EinlagenS + " " + "CHF" + " " + "eingezahlt");
    String bezeichnung = "Einzahlung";   
    
        if(einlage.getText().equals("")){
            JOptionPane.showMessageDialog(this, "Please fill in the empty field");
        } else {
        String Daten [] = {formattedDatum, bezeichnung, "",einlage.getText()};
            tblModel.addRow(Daten);
            einlage.setText("");
        }
} catch (ParseException e) {
    // Fehlerbehandlung, wenn das Datum nicht im erwarteten Format ist
    System.out.println("Ungültiges Datumsformat: " + datum);
    e.printStackTrace();

}
    }//GEN-LAST:event_einzahlenActionPerformed

    private void jRadioButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton3ActionPerformed
        if (jRadioButton3.isSelected()) {
            auszahlung.setEnabled(false);
            einlage.setEnabled(false);
            zinssatz.setEnabled(true);
            einzahlen.setEnabled(false);
            auszahlen.setEnabled(false);
            zinsändern.setEnabled(true);
=======
    private void jRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton2ActionPerformed
        if (jRadioButton2.isSelected()) {
            jTextField7.setEnabled(false);
            jTextField8.setEnabled(true);
            jTextField6.setEnabled(false);
            jButton3.setEnabled(true);
            jButton2.setEnabled(false);
            jButton4.setEnabled(false);

        }
    }//GEN-LAST:event_jRadioButton2ActionPerformed

    private void jRadioButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton3ActionPerformed
        if (jRadioButton3.isSelected()) {
            jTextField7.setEnabled(false);
            jTextField8.setEnabled(false);
            jTextField6.setEnabled(true);
            jButton3.setEnabled(false);
            jButton2.setEnabled(false);
            jButton4.setEnabled(true);
>>>>>>> c84378042d77448b19c911bc78cd7f4c6129efb1

        }
    }//GEN-LAST:event_jRadioButton3ActionPerformed

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
        if (jRadioButton1.isSelected()) {
<<<<<<< HEAD
            auszahlung.setEnabled(true);
            einlage.setEnabled(false);
            zinssatz.setEnabled(false);
            einzahlen.setEnabled(false);
            auszahlen.setEnabled(true);
            zinsändern.setEnabled(false);
        }
    }//GEN-LAST:event_jRadioButton1ActionPerformed

    private void jRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton2ActionPerformed
        if (jRadioButton2.isSelected()) {
            auszahlung.setEnabled(false);
            einlage.setEnabled(true);
            zinssatz.setEnabled(false);
            einzahlen.setEnabled(true);
            auszahlen.setEnabled(false);
            zinsändern.setEnabled(false);

        }
    }//GEN-LAST:event_jRadioButton2ActionPerformed

    private void zinsändernActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_zinsändernActionPerformed
        DateFormat dateFormat = new SimpleDateFormat("dd.MM.yyyy");
        Date date = new Date();

        String ZinssatzS = zinssatz.getText();
        Zinssatz = Double.parseDouble(ZinssatzS);
        while (Zähler < 2) {
            Zinssatz = Zinssatz / 100;
            Zähler = 2;
        }

        jLabel11.setText("Sie haben am" + " " + dateFormat.format(date) + " " + " " + "den Zinssatz zu" + " " + ZinssatzS + "%" + " " + "geändert");

        String bezeichnung = "Zinsänderung";
        LocalDate datum = java.time.LocalDate.now();
        Date lokalesDatum = Date.from(datum.atStartOfDay(ZoneId.systemDefault()).toInstant());
        String formattedDatum = dateFormat.format(lokalesDatum);
        
        if(zinssatz.getText().equals("")){
            JOptionPane.showMessageDialog(this, "Please fill in the empty field");
        } else {
        String Daten [] = {formattedDatum, bezeichnung, zinssatz.getText(), ""};
            DefaultTableModel tblModel = (DefaultTableModel)tablePensionBut.getModel();   
            tblModel.addRow(Daten);
            zinssatz.setText("");
        }
    }//GEN-LAST:event_zinsändernActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        
        String vorname = jTextField1.getText();
        String nachname = jTextField2.getText();
        String wohnort = jTextField4.getText();
        String plz = jTextField3.getText();
        String saldo = Double.toString(Saldo);
        String path = "";
        JFileChooser pdf = new JFileChooser();
        pdf.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        int x = pdf.showSaveDialog(this);

        if (x == JFileChooser.APPROVE_OPTION) {
            path = pdf.getSelectedFile().getPath();
        }
        
         String fileName = JOptionPane.showInputDialog(null, "Enter the file name (without extension):");

        if (fileName == null || fileName.trim().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Invalid file name. PDF not created.");
            return;
        }

        String filePath = path + "/" + fileName + ".pdf";

        Document doc = new Document();
        try {
            PdfWriter.getInstance(doc, new FileOutputStream(filePath));

            doc.open();
            
            Paragraph pVorname = new Paragraph("Vorname: " + vorname);
            Paragraph pNachname = new Paragraph("Nachname: " + nachname);
            Paragraph pWohnort = new Paragraph("Wohnort: " + wohnort);
            Paragraph pPLZ = new Paragraph("Postleitzahl: " + plz);
            Paragraph abstand = new Paragraph(Chunk.NEWLINE);
            doc.add(pVorname);
            doc.add(pNachname);
            doc.add(pWohnort);
            doc.add(pPLZ);
            doc.add(abstand);
            

            PdfPTable tbl = new PdfPTable(4);

            PdfPCell headerCell1 = new PdfPCell(new Phrase("Datum"));
            headerCell1.setBackgroundColor(Color.GRAY.brighter());
            headerCell1.setHorizontalAlignment(Element.ALIGN_CENTER);

            PdfPCell headerCell2 = new PdfPCell(new Phrase("Bezeichnung"));
            headerCell2.setBackgroundColor(Color.GRAY.brighter());
            headerCell2.setHorizontalAlignment(Element.ALIGN_CENTER);

            PdfPCell headerCell3 = new PdfPCell(new Phrase("Zins"));
            headerCell3.setBackgroundColor(Color.GRAY.brighter());
            headerCell3.setHorizontalAlignment(Element.ALIGN_CENTER);
                       
            PdfPCell headerCell4 = new PdfPCell(new Phrase("Betrag"));
            headerCell4.setBackgroundColor(Color.GRAY.brighter());
            headerCell4.setHorizontalAlignment(Element.ALIGN_CENTER);



            // Add the column headers to the table
            tbl.addCell(headerCell1);
            tbl.addCell(headerCell2);
            tbl.addCell(headerCell3);
            tbl.addCell(headerCell4);

            for (int i = 0; i < tablePensionBut.getRowCount(); i++) {
                String tabletext1 = tablePensionBut.getValueAt(i, 0).toString();
                String tabletext2 = tablePensionBut.getValueAt(i, 1).toString();
                String tabletext3 = tablePensionBut.getValueAt(i, 2).toString();
                String tabletext4 = tablePensionBut.getValueAt(i, 3).toString();

                tbl.addCell(tabletext1);
                tbl.addCell(tabletext2);
                tbl.addCell(tabletext3);
                tbl.addCell(tabletext4);
            }

            doc.add(tbl);
            Paragraph pdfSaldo = new Paragraph("Saldo: " + saldo);
            doc.add(pdfSaldo);
        } catch (FileNotFoundException | DocumentException ex) {
            Logger.getLogger(Kapitalrechner.class.getName()).log(Level.SEVERE, null, ex);
        }

        

        doc.close();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void zinssatzFeldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_zinssatzFeldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_zinssatzFeldActionPerformed

    private void datumFeldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_datumFeldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_datumFeldActionPerformed
    
    private void jTextField5Buchstaben(int maxLength) {
        ((AbstractDocument) startkapital.getDocument()).setDocumentFilter(new DocumentFilter() {
            @Override
            public void insertString(DocumentFilter.FilterBypass fb, int offset, String text, AttributeSet attrs) throws BadLocationException {
                String newText = fb.getDocument().getText(0, fb.getDocument().getLength()) + text;
                try {
                    double number = Double.parseDouble(newText);
                    if (number >= 0 && number <= Double.MAX_VALUE && ("" + number).length() <= maxLength) {
                        super.insertString(fb, offset, text, attrs);
                    }
                } catch (NumberFormatException e) {
                    // ignore non-double input
                }
            }

            @Override
            public void replace(DocumentFilter.FilterBypass fb, int offset, int length, String text, AttributeSet attrs) throws BadLocationException {
                String newText = fb.getDocument().getText(0, fb.getDocument().getLength()) + text;
                if (newText.equals("-") && maxLength > 0) {
                    super.replace(fb, offset, length, text, attrs);
                    return;
                }
                try {
                    double number = Double.parseDouble(newText);
                    if (number >= 0 && number <= Double.MAX_VALUE && ("" + number).length() <= maxLength) {
                        super.replace(fb, offset, length, text, attrs);
                    }
                } catch (NumberFormatException e) {
                    // ignore non-double input
                }
            }
        });
    }
    
    private void jTextField3Buchstaben(int maxLength) {
        ((AbstractDocument) jTextField3.getDocument()).setDocumentFilter(new DocumentFilter() {
=======
            jTextField7.setEnabled(true);
            jTextField8.setEnabled(false);
            jTextField6.setEnabled(false);
            jButton3.setEnabled(false);
            jButton2.setEnabled(true);
            jButton4.setEnabled(false);
        }
    }//GEN-LAST:event_jRadioButton1ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        jLabel9.setText("Dein Saldo beträgt:" + " " + Resultat);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        String startkapital = jTextField5.getText();
        Startkapital = Double.parseDouble(startkapital);
        String einzahlen = jTextField8.getText();
        Einlagen = Double.parseDouble(einzahlen);
        Resultat = Startkapital + Einlagen;

    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        String startkapital = jTextField5.getText();
        Startkapital = Double.parseDouble(startkapital);
        String auszahlen = jTextField8.getText();
        Auszahlung = Double.parseDouble(auszahlen);
        Resultat = Startkapital - Auszahlung;
    }//GEN-LAST:event_jButton2ActionPerformed
    private void jTextField5Buchstaben(int maxLength) {
        ((AbstractDocument) jTextField5.getDocument()).setDocumentFilter(new DocumentFilter() {
>>>>>>> c84378042d77448b19c911bc78cd7f4c6129efb1
            @Override
            public void insertString(DocumentFilter.FilterBypass fb, int offset, String text, AttributeSet attrs) throws BadLocationException {
                String newText = fb.getDocument().getText(0, fb.getDocument().getLength()) + text;
                try {
                    double number = Double.parseDouble(newText);
                    if (number >= 0 && number <= Double.MAX_VALUE && ("" + number).length() <= maxLength) {
                        super.insertString(fb, offset, text, attrs);
                    }
                } catch (NumberFormatException e) {
                    // ignore non-double input
                }
            }

            @Override
            public void replace(DocumentFilter.FilterBypass fb, int offset, int length, String text, AttributeSet attrs) throws BadLocationException {
                String newText = fb.getDocument().getText(0, fb.getDocument().getLength()) + text;
                if (newText.equals("-") && maxLength > 0) {
                    super.replace(fb, offset, length, text, attrs);
                    return;
                }
                try {
                    double number = Double.parseDouble(newText);
                    if (number >= 0 && number <= Double.MAX_VALUE && ("" + number).length() <= maxLength) {
                        super.replace(fb, offset, length, text, attrs);
                    }
                } catch (NumberFormatException e) {
                    // ignore non-double input
                }
            }
        });
    }

    private void jTextField8Buchstaben(int maxLength) {
<<<<<<< HEAD
        ((AbstractDocument) einlage.getDocument()).setDocumentFilter(new DocumentFilter() {
=======
        ((AbstractDocument) jTextField8.getDocument()).setDocumentFilter(new DocumentFilter() {
>>>>>>> c84378042d77448b19c911bc78cd7f4c6129efb1
            @Override
            public void insertString(DocumentFilter.FilterBypass fb, int offset, String text, AttributeSet attrs) throws BadLocationException {
                String newText = fb.getDocument().getText(0, fb.getDocument().getLength()) + text;
                try {
                    double number = Double.parseDouble(newText);
                    if (number >= 0 && number <= Double.MAX_VALUE && ("" + number).length() <= maxLength) {
                        super.insertString(fb, offset, text, attrs);
                    }
                } catch (NumberFormatException e) {
                    // ignore non-double input
                }
            }

            @Override
            public void replace(DocumentFilter.FilterBypass fb, int offset, int length, String text, AttributeSet attrs) throws BadLocationException {
                String newText = fb.getDocument().getText(0, fb.getDocument().getLength()) + text;
                if (newText.equals("-") && maxLength > 0) {
                    super.replace(fb, offset, length, text, attrs);
                    return;
                }
                try {
                    double number = Double.parseDouble(newText);
                    if (number >= 0 && number <= Double.MAX_VALUE && ("" + number).length() <= maxLength) {
                        super.replace(fb, offset, length, text, attrs);
                    }
                } catch (NumberFormatException e) {
                    // ignore non-double input
                }
            }
        });
    }

    private void jTextField7Buchstaben(int maxLength) {
<<<<<<< HEAD
        ((AbstractDocument) auszahlung.getDocument()).setDocumentFilter(new DocumentFilter() {
=======
        ((AbstractDocument) jTextField7.getDocument()).setDocumentFilter(new DocumentFilter() {
>>>>>>> c84378042d77448b19c911bc78cd7f4c6129efb1
            @Override
            public void insertString(DocumentFilter.FilterBypass fb, int offset, String text, AttributeSet attrs) throws BadLocationException {
                String newText = fb.getDocument().getText(0, fb.getDocument().getLength()) + text;
                try {
                    double number = Double.parseDouble(newText);
                    if (number >= 0 && number <= Double.MAX_VALUE && ("" + number).length() <= maxLength) {
                        super.insertString(fb, offset, text, attrs);
                    }
                } catch (NumberFormatException e) {
                    // ignore non-double input
                }
            }

            @Override
            public void replace(DocumentFilter.FilterBypass fb, int offset, int length, String text, AttributeSet attrs) throws BadLocationException {
                String newText = fb.getDocument().getText(0, fb.getDocument().getLength()) + text;
                if (newText.equals("-") && maxLength > 0) {
                    super.replace(fb, offset, length, text, attrs);
                    return;
                }
                try {
                    double number = Double.parseDouble(newText);
                    if (number >= 0 && number <= Double.MAX_VALUE && ("" + number).length() <= maxLength) {
                        super.replace(fb, offset, length, text, attrs);
                    }
                } catch (NumberFormatException e) {
                    // ignore non-double input
                }
            }
        });
    }

    private void jTextField6Buchstaben(int maxLength) {
<<<<<<< HEAD
        ((AbstractDocument) zinssatz.getDocument()).setDocumentFilter(new DocumentFilter() {
=======
        ((AbstractDocument) jTextField6.getDocument()).setDocumentFilter(new DocumentFilter() {
>>>>>>> c84378042d77448b19c911bc78cd7f4c6129efb1
            @Override
            public void insertString(DocumentFilter.FilterBypass fb, int offset, String text, AttributeSet attrs) throws BadLocationException {
                String newText = fb.getDocument().getText(0, fb.getDocument().getLength()) + text;
                try {
                    double number = Double.parseDouble(newText);
                    if (number >= 0 && number <= Double.MAX_VALUE && ("" + number).length() <= maxLength) {
                        super.insertString(fb, offset, text, attrs);
                    }
                } catch (NumberFormatException e) {
                    // ignore non-double input
                }
            }

            @Override
            public void replace(DocumentFilter.FilterBypass fb, int offset, int length, String text, AttributeSet attrs) throws BadLocationException {
                String newText = fb.getDocument().getText(0, fb.getDocument().getLength()) + text;
                if (newText.equals("-") && maxLength > 0) {
                    super.replace(fb, offset, length, text, attrs);
                    return;
                }
                try {
                    double number = Double.parseDouble(newText);
                    if (number >= 0 && number <= Double.MAX_VALUE && ("" + number).length() <= maxLength) {
                        super.replace(fb, offset, length, text, attrs);
                    }
                } catch (NumberFormatException e) {
                    // ignore non-double input
                }
            }
        });
    }

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Kapitalrechner.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Kapitalrechner.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Kapitalrechner.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Kapitalrechner.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Kapitalrechner().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
<<<<<<< HEAD
    private javax.swing.JButton auszahlen;
    private javax.swing.JTextField auszahlung;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JTextField datumFeld;
    private javax.swing.JTextField einlage;
    private javax.swing.JButton einzahlen;
    private javax.swing.JPanel head;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
=======
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JPanel head;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
>>>>>>> c84378042d77448b19c911bc78cd7f4c6129efb1
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
<<<<<<< HEAD
=======
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
>>>>>>> c84378042d77448b19c911bc78cd7f4c6129efb1
    private javax.swing.JLabel jLabel9;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
<<<<<<< HEAD
    private javax.swing.JScrollPane jScrollPane1;
=======
>>>>>>> c84378042d77448b19c911bc78cd7f4c6129efb1
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
<<<<<<< HEAD
    private javax.swing.JTextField startkapital;
    private javax.swing.JTable tablePensionBut;
    private javax.swing.JLabel titel;
    private javax.swing.JTextField zinssatz;
    private javax.swing.JTextField zinssatzFeld;
    private javax.swing.JButton zinsändern;
=======
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JLabel titel;
>>>>>>> c84378042d77448b19c911bc78cd7f4c6129efb1
    // End of variables declaration//GEN-END:variables
}
