
import javax.swing.text.AbstractDocument;
import javax.swing.text.AttributeSet;
import javax.swing.text.BadLocationException;
import javax.swing.text.DocumentFilter;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author KASC05
 */
public class PensionBut extends javax.swing.JFrame {

    int Startkapital;
    int SparbetragJahr;
    int SparbetragJahrDauer;
    int SparbetragMonat;
    int EinzahltagSparbetragMonat;
    int Zinsbetrag;

    @SuppressWarnings("empty-statement")
    public PensionBut() {
        initComponents();
        EinzahltagSpinner.setEnabled(false);
        SparbetragMonatTextField.setEnabled(false);
        DauerSpinner.setEnabled(false);
        SparbetragTextField.setEnabled(false);
        ZinsbetragTextField.setEnabled(false);
        keineBuchstabenImStartkapitalTextField(10);
        keineBuchstabenImSparbetragTextField(10);
        keineBuchstabenImSparbetragMonatTextField(10);
        keineBuchstabenImZinsbetrag(10);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        yearMonthGroup = new javax.swing.ButtonGroup();
        jPanel4 = new javax.swing.JPanel();
        AnfangEndeJahr = new javax.swing.ButtonGroup();
        AnfangEndeMonat = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        head = new javax.swing.JPanel();
        titel = new javax.swing.JLabel();
        monthlyRB = new javax.swing.JRadioButton();
        yearlyRB = new javax.swing.JRadioButton();
        StartkapitalLabel = new javax.swing.JLabel();
        SpeichernButton = new javax.swing.JButton();
        SparbetragMonatTextField = new javax.swing.JTextField();
        SparbetragLabel = new javax.swing.JLabel();
        DauerSpinner = new javax.swing.JSpinner();
        SparbetragMonatLabel = new javax.swing.JLabel();
        DauerLabel2 = new javax.swing.JLabel();
        EinzahltagSpinner = new javax.swing.JSpinner();
        DauerLabel1 = new javax.swing.JLabel();
        SparbetragTextField = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        ZinsbetragTextField = new javax.swing.JTextField();
        StartkapitalTextField = new javax.swing.JTextField();
        DauerLabel = new javax.swing.JLabel();
        AnfangJahrRB = new javax.swing.JRadioButton();
        EndeJahrRB = new javax.swing.JRadioButton();
        EndeMonatRB = new javax.swing.JRadioButton();
        AnfangMonatRB = new javax.swing.JRadioButton();

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        head.setBackground(new java.awt.Color(51, 188, 209));

        titel.setBackground(new java.awt.Color(0, 0, 0));
        titel.setFont(new java.awt.Font("Lucida Console", 0, 48)); // NOI18N
        titel.setText("Sparer");

        javax.swing.GroupLayout headLayout = new javax.swing.GroupLayout(head);
        head.setLayout(headLayout);
        headLayout.setHorizontalGroup(
            headLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headLayout.createSequentialGroup()
                .addGap(94, 94, 94)
                .addComponent(titel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        headLayout.setVerticalGroup(
            headLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headLayout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addComponent(titel)
                .addContainerGap(65, Short.MAX_VALUE))
        );

        yearMonthGroup.add(monthlyRB);
        monthlyRB.setText("Monatlich");
        monthlyRB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                monthlyRBActionPerformed(evt);
            }
        });

        yearMonthGroup.add(yearlyRB);
        yearlyRB.setText("Jährlich");
        yearlyRB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yearlyRBActionPerformed(evt);
            }
        });

        StartkapitalLabel.setText("Startkapital");

        SpeichernButton.setText("Zins berechnen");
        SpeichernButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SpeichernButtonActionPerformed(evt);
            }
        });

        SparbetragMonatTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SparbetragMonatTextFieldActionPerformed(evt);
            }
        });

        SparbetragLabel.setText("Jährlicher Sparbetrag");

        DauerSpinner.setModel(new javax.swing.SpinnerNumberModel(1, 1, 99, 1));
        DauerSpinner.setFocusable(false);
        DauerSpinner.setMaximumSize(new java.awt.Dimension(12, 12));
        DauerSpinner.setMinimumSize(new java.awt.Dimension(0, 0));
        DauerSpinner.setRequestFocusEnabled(false);
        DauerSpinner.setValue(1);

        SparbetragMonatLabel.setText("Monatlicher Sparbetrag");

        DauerLabel2.setText("Tag im Monat");

        EinzahltagSpinner.setModel(new javax.swing.SpinnerNumberModel(1, 1, 31, 1));

        DauerLabel1.setText("Einzahltag:");

        jLabel1.setText("Zinssatz");

        StartkapitalTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StartkapitalTextFieldActionPerformed(evt);
            }
        });

        DauerLabel.setText("Dauer (Jahre):");

        AnfangEndeJahr.add(AnfangJahrRB);
        AnfangJahrRB.setText("Anfang des Jahres");
        AnfangJahrRB.setEnabled(false);
        AnfangJahrRB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AnfangJahrRBActionPerformed(evt);
            }
        });

        AnfangEndeJahr.add(EndeJahrRB);
        EndeJahrRB.setText("Ende des Jahres");
        EndeJahrRB.setEnabled(false);

        AnfangEndeMonat.add(EndeMonatRB);
        EndeMonatRB.setText("Ende des Monats");
        EndeMonatRB.setEnabled(false);

        AnfangEndeMonat.add(AnfangMonatRB);
        AnfangMonatRB.setText("Anfang des Monats");
        AnfangMonatRB.setEnabled(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(head, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(97, 97, 97)
                                .addComponent(yearlyRB)
                                .addGap(309, 309, 309)
                                .addComponent(monthlyRB))
                            .addComponent(SpeichernButton))
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(AnfangJahrRB)
                            .addComponent(StartkapitalLabel)
                            .addComponent(StartkapitalTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(8, 8, 8)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(EndeJahrRB)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(SparbetragLabel)
                                        .addGap(35, 35, 35)))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(7, 7, 7)
                                        .addComponent(DauerLabel)
                                        .addGap(72, 72, 72)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(SparbetragMonatTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(SparbetragMonatLabel)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(DauerLabel2))))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(123, 123, 123)
                                        .addComponent(AnfangMonatRB)
                                        .addGap(39, 39, 39)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(DauerLabel1)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(EinzahltagSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(EndeMonatRB)))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(SparbetragTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(42, 42, 42)
                                .addComponent(DauerSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(142, 142, 142)
                                .addComponent(jLabel1))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 88, Short.MAX_VALUE)
                                .addComponent(ZinsbetragTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(132, 132, 132))))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(head, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(yearlyRB)
                    .addComponent(monthlyRB))
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AnfangJahrRB)
                    .addComponent(EndeJahrRB)
                    .addComponent(AnfangMonatRB)
                    .addComponent(EndeMonatRB))
                .addGap(76, 76, 76)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(StartkapitalLabel)
                    .addComponent(SparbetragLabel)
                    .addComponent(DauerLabel)
                    .addComponent(SparbetragMonatLabel)
                    .addComponent(DauerLabel2)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SparbetragTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(StartkapitalTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DauerSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SparbetragMonatTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DauerLabel1)
                    .addComponent(EinzahltagSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ZinsbetragTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 182, Short.MAX_VALUE)
                .addComponent(SpeichernButton)
                .addGap(28, 28, 28))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void StartkapitalTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StartkapitalTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_StartkapitalTextFieldActionPerformed

    private void SparbetragMonatTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SparbetragMonatTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SparbetragMonatTextFieldActionPerformed

    private void SpeichernButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SpeichernButtonActionPerformed

        String startkapital = StartkapitalTextField.getText();

        if ("".equals(startkapital)) {
            System.out.println("Kein Wert");
        } else {
            Startkapital = Integer.parseInt(startkapital);
            System.out.println(Startkapital);
        }

        String sparbetragMonat = SparbetragMonatTextField.getText();

        if ("".equals(sparbetragMonat)) {
            System.out.println("Kein Wert");
        } else {
            SparbetragMonat = Integer.parseInt(sparbetragMonat);
            System.out.println(SparbetragMonat);
        }

        int einzahltag = (int) EinzahltagSpinner.getValue();
        EinzahltagSparbetragMonat = einzahltag;
        System.out.println(EinzahltagSparbetragMonat);

        String sparbetrag = SparbetragTextField.getText();

        if ("".equals(sparbetrag)) {
            System.out.println("Kein Wert");
        } else {
            SparbetragJahr = Integer.parseInt(sparbetrag);
            System.out.println(SparbetragJahr);
        }

        int dauer = (int) DauerSpinner.getValue();
        SparbetragJahrDauer = dauer;
        System.out.println(SparbetragJahrDauer);

        String zinsbetrag = ZinsbetragTextField.getText();

        if ("".equals(zinsbetrag)) {
            System.out.println("Kein Wert");
        } else {
            Zinsbetrag = Integer.parseInt(zinsbetrag);
            System.out.println(Zinsbetrag);
        }

    }//GEN-LAST:event_SpeichernButtonActionPerformed

    private void yearlyRBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yearlyRBActionPerformed
        if (yearlyRB.isSelected()) {
            DauerSpinner.setEnabled(true);
            SparbetragTextField.setEnabled(true);
            EinzahltagSpinner.setEnabled(false);
            SparbetragMonatTextField.setEnabled(false);
            ZinsbetragTextField.setEnabled(true);
            AnfangJahrRB.setEnabled(true);
            EndeJahrRB.setEnabled(true);
            AnfangMonatRB.setEnabled(false);
            EndeMonatRB.setEnabled(false);
            
        }
    }//GEN-LAST:event_yearlyRBActionPerformed

    private void monthlyRBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_monthlyRBActionPerformed
        if (monthlyRB.isSelected()) {
            EinzahltagSpinner.setEnabled(true);
            SparbetragMonatTextField.setEnabled(true);
            DauerSpinner.setEnabled(false);
            SparbetragTextField.setEnabled(false);
            ZinsbetragTextField.setEnabled(true);
            AnfangMonatRB.setEnabled(true);
            EndeMonatRB.setEnabled(true);
            AnfangJahrRB.setEnabled(false);
            EndeJahrRB.setEnabled(false);

        }
    }//GEN-LAST:event_monthlyRBActionPerformed

    private void AnfangJahrRBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AnfangJahrRBActionPerformed

    }//GEN-LAST:event_AnfangJahrRBActionPerformed




    private void keineBuchstabenImZinsbetrag(int maxLength) {
        ((AbstractDocument) ZinsbetragTextField.getDocument()).setDocumentFilter(new DocumentFilter() {
            @Override
            public void insertString(DocumentFilter.FilterBypass fb, int offset, String text, AttributeSet attrs) throws BadLocationException {
                if (text.matches("[0-9]+") && (fb.getDocument().getLength() + text.length()) <= maxLength) {
                    super.insertString(fb, offset, text, attrs);
                }
            }

            @Override
            public void replace(DocumentFilter.FilterBypass fb, int offset, int length, String text, AttributeSet attrs) throws BadLocationException {
                if (text.matches("[0-9]+") && (fb.getDocument().getLength() + text.length() - length) <= maxLength) {
                    super.replace(fb, offset, length, text, attrs);
                }
            }
        });
    }
    
    private void keineBuchstabenImSparbetragMonatTextField(int maxLength) {
        ((AbstractDocument) SparbetragMonatTextField.getDocument()).setDocumentFilter(new DocumentFilter() {
            @Override
            public void insertString(DocumentFilter.FilterBypass fb, int offset, String text, AttributeSet attrs) throws BadLocationException {
                if (text.matches("[0-9]+") && (fb.getDocument().getLength() + text.length()) <= maxLength) {
                    super.insertString(fb, offset, text, attrs);
                }
            }

            @Override
            public void replace(DocumentFilter.FilterBypass fb, int offset, int length, String text, AttributeSet attrs) throws BadLocationException {
                if (text.matches("[0-9]+") && (fb.getDocument().getLength() + text.length() - length) <= maxLength) {
                    super.replace(fb, offset, length, text, attrs);
                }
            }
        });
    }

    private void keineBuchstabenImSparbetragTextField(int maxLength) {
        ((AbstractDocument) SparbetragTextField.getDocument()).setDocumentFilter(new DocumentFilter() {
            @Override
            public void insertString(DocumentFilter.FilterBypass fb, int offset, String text, AttributeSet attrs) throws BadLocationException {
                if (text.matches("[0-9]+") && (fb.getDocument().getLength() + text.length()) <= maxLength) {
                    super.insertString(fb, offset, text, attrs);
                }
            }

            @Override
            public void replace(DocumentFilter.FilterBypass fb, int offset, int length, String text, AttributeSet attrs) throws BadLocationException {
                if (text.matches("[0-9]+") && (fb.getDocument().getLength() + text.length() - length) <= maxLength) {
                    super.replace(fb, offset, length, text, attrs);
                }
            }
        });
    }

    private void keineBuchstabenImStartkapitalTextField(int maxLength) {
        ((AbstractDocument) StartkapitalTextField.getDocument()).setDocumentFilter(new DocumentFilter() {
            @Override
            public void insertString(DocumentFilter.FilterBypass fb, int offset, String text, AttributeSet attrs) throws BadLocationException {
                if (text.matches("[0-9]+") && (fb.getDocument().getLength() + text.length()) <= maxLength) {
                    super.insertString(fb, offset, text, attrs);
                }
            }

            @Override
            public void replace(DocumentFilter.FilterBypass fb, int offset, int length, String text, AttributeSet attrs) throws BadLocationException {
                if (text.matches("[0-9]+") && (fb.getDocument().getLength() + text.length() - length) <= maxLength) {
                    super.replace(fb, offset, length, text, attrs);
                }
            }
        });
    }


    /**
     * @param args the command line arguments
     */
    @SuppressWarnings("Convert2Lambda")
    public static void main(String args[]) {

        java.awt.EventQueue.invokeLater(new Runnable() {
            @SuppressWarnings("override")
            public void run() {
                new PensionBut().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup AnfangEndeJahr;
    private javax.swing.ButtonGroup AnfangEndeMonat;
    private javax.swing.JRadioButton AnfangJahrRB;
    private javax.swing.JRadioButton AnfangMonatRB;
    private javax.swing.JLabel DauerLabel;
    private javax.swing.JLabel DauerLabel1;
    private javax.swing.JLabel DauerLabel2;
    private javax.swing.JSpinner DauerSpinner;
    private javax.swing.JSpinner EinzahltagSpinner;
    private javax.swing.JRadioButton EndeJahrRB;
    private javax.swing.JRadioButton EndeMonatRB;
    private javax.swing.JLabel SparbetragLabel;
    private javax.swing.JLabel SparbetragMonatLabel;
    private javax.swing.JTextField SparbetragMonatTextField;
    private javax.swing.JTextField SparbetragTextField;
    private javax.swing.JButton SpeichernButton;
    private javax.swing.JLabel StartkapitalLabel;
    private javax.swing.JTextField StartkapitalTextField;
    private javax.swing.JTextField ZinsbetragTextField;
    private javax.swing.JPanel head;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JRadioButton monthlyRB;
    private javax.swing.JLabel titel;
    private javax.swing.ButtonGroup yearMonthGroup;
    private javax.swing.JRadioButton yearlyRB;
    // End of variables declaration//GEN-END:variables
}
